### ISSUE TITLE
Installiation problems on M1 Mac 

### ISSUE THREAD

**Issue by conorhassan** [DPBayes/d3p#2]
Hi there, 

I am trying to install `d3p` and am getting the following error:

```
ERROR: Could not build wheels for jax-chacha-prng, which is required to install pyproject.toml-based projects
```

I have never seen this type of error before. It would be great if I could have some guidance to resolve this. 

Thanks, 
Conor

**Comment by lumip** [comment]
Hey. This appears to be a problem installing a dependency of d3p, namely https://github.com/DPBayes/jax-chacha-prng . That one relies on native code and does currently not come with precompiled packages for M1 Macs. While in principle the package manager should be able to compile it during the installation, this seems to encounter some error for you.

We will look into this, but any additional information you can provide us with would be helpful.
What is the exact command you used for installing?
Is there any more detailed information about the error message (ideally you can provide a full console log of the installation progress)?
